### ISSUE TITLE
On-cluster build: builder image required in func.yaml

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#1005]
Currently, because we have defaults for the builder images, they are not set in `func.yaml` for functions created using the default builtin templates. However, the builder image name is required when running builds on the cluster. This causes friction with new projects, requiring the developer to manually set this value in the `func.yaml` configuration file. When it is not set, the following error occurs when the pipeline runs.
```
failed to create task run pod "viewer-git-pipeline-run-88t7b-build": missing field(s): steps[1].Image. Maybe missing or invalid Task default/func-buildpacks
```
/kind bug

**Comment by lkingland** [comment]
As we're discussing elsewhere, requiring that these values always be set in the `func.yaml` (rather than treat it as an override) causes some tangential challenges.  For example, how do we update default builders without invalidating previously created Functions?
I think the core problem here is that our Tekton pipeline is expecting that func.yaml include a defined builder, before the user has ever actually built (and thus has not chosen S2I or Buildpack).
The correct solution, architecturally, would be to keep the `func` codebase "in the loop" when building, because it may include additional logic in the future to assist with building a project.  If we set the precident now that a "previously unbuilt Funciton" can be picked up by a Tekton task and built without that codebase's assistance, than we are either going to lose functionality, or require duplicated functionality.
With that caviat in place, I understand this could be considered something of a special case, where `func` can no build in this environment due to a missing daemon, or other reasons.  In that case, a compromise might be in order.  However, perhaps we can compromise in a way that keeps the original intent intact.
Could we provide this information to Tekton via some other avenue?  Could we still use `func` in the process, _sans_ actually building?  could we implement a new "build strategy" called `func build --builder tekton`?
If we explore all other avenues, and just can't make it work, then prepopulating the `func.yaml` with builders may be the only option!
