### ISSUE TITLE
e2e Testing

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#338]
It would be great to have e2e testing that simulates user experience with func cli (e.g func create, func deploy, func list, etc.) 
E2E would include (but not limited to) scenarios as deploy and redeploy functions in all run-times for either ttp and event triggered functions.

**Comment by lkingland** [comment]
Thank you for the suggestion Jrangleramos, but I do want to issue a few words of caution, and perhaps steer your contributions towards improving unit and integration tests, because it is my experience that E2E tests have a low value per unit of work invested, and end up often having unintended negative side-effects down the road!

E2E tests tend to be a catch-all for testing systems which do not have proper unit and integration tests, were not developed with testability in mind, or have proper isolation of concerns.  This manifests itself as E2E tests 1) testing what should be implementation details 2) being hyper-specific to a particular use-case causing duplicate code 2) and are generally incomplete when compared with proper Unit+Integration tests.

**E2E tests tend to be a slippery slope** to testing for implementation detal far outside the purview of the "cli" itself.  For instance, why is the CLI responsible for ensuring that the buildpack-created Function framework for Golang exposes readiness and health endpoints?  That should be integration tests within the buildpacks codebase.  The CLI should stick to CLI-things.

Secondly, **E2E test tend to become myopic** about the use case exposed by the binary.  Investing in E2E tests for one binary creates a split-brain situation where it is not clear where to test for certain features.  In a system whose sole purpose is to be a CLI, that may be less of a problem (though still suffers from the other two), in a system like ours where we want to be widely applicable in a range of scenarios:  A KN plugin, a standalone binary, an IDE plugin, a library for 3rd party integrations, an implementing library in a Functions operator, etc.  The tests should be as close to the functionality they are testing as possible:  that means client integration tests.

Thirdly, **E2E tests are not complete and give a false sense of security**.  When setting up an E2E test, it requires creating an environment with a very small margin of error: everything must work.  This is fine for what it does:  test that when everything is working, everything works, but it is far more complete to create a CLI with a mock implementation of a backing service, which can then simulate every possible failure mode, ensuring the CLI behaves itself even in adverse conditions.

These are the three big reasons I see E2E tests as being either not useful in a properly architected system, or actually harmful.  There are other reasons as well, such as introducing multiple external dependencies to the build/test process, slowness, and generally creating a lot of extra code to support that would be better spent making the unit and integration tests solid.    Fortunately for us we have developed Func with _strict_ testability and modularity as primary concerns.  This gives us the luxury of being able to reach full coverage and high confidence through Unit+Integration tests.

All this said, I would not be opposed to a few E2E tests in the system that are extremely focused, and do not add much complexity to the overall system, as a failsafe/backup.  I am also always looking to be proved wrong, and for contradicting opinions, so I am all ears if the avove diatribe does not ring true to you!  However, I would suggest we focus our energies on an ever expanding and improving set of unit and integration tests.

**Comment by mgencur** [comment]
Hi @lkingland , I'll try to provide more detailed answer later and also provide some more use cases where E2E will help but here's a few that I can think of right now:
* The E2E are the top of the [test pyramid](https://martinfowler.com/articles/practical-test-pyramid.html#End-to-endTests), a small set of tests that execute the complete path through the program execution. There should be many more unit tests and integration tests. But E2E are an important part to make sure the system is working end to end. (I think this is clear to every one so I'm still thinking why this pushback on the smaller set of E2E that are brought through this PR).
* E2E are required to be executed downstream to make sure that everything was OK through productization process. But having those tests upstream makes it easier to achieve CI/CD. Having tests upstream which are updated continuously and then only run the same tests in the downstream pipeline, without the need to fix/correct tests late in the release cycle. If we have those tests only downstream, it brings a little waterfall to the process because the tests need to be maintained (made compatible) later.
* All Knative projects have E2E tests, this fact in itself is a good indicator that projects don't go the wrong way when they actually implement them. Forgive me my lack of knowledge of internal details of this whole project but I'd be surprised if this project was so different from others that it actually doesn't need any E2E.
* This E2E test suite really brings just a few tests, it's not a huge test suite with hundreds of tests. So, IMO, it's really the top of the pyramid. And as such, it should not be a problem to maintain them (we'd be of course playing a part in that).

**Comment by lkingland** [comment]
Thanks for your comments @mgencur, and thank you again for the contributions @jrangelramos.  
I agree with you!  I fear that the larger, implicit goal of my comments above may have been overshadowed by my long-winded justifcation for keeping E2E tests small.
> All this said, I would not be opposed to a few E2E tests in the system
The primary purpose of my comments here is to **lay some justification for why I had so many suggested changes in the associated PR**.  I want it to be clear that I appreciate the contribution, and have no problems with the code itself, but rather that my suggestions all boil down to a general principle:  most test functionality should exist near the features themselves, in unit and integration tests, keeping E2E tests as focused as possible.
The top of the pyramid should be smaller than the lower sections.
I want to reiterate that I am happy with some E2Es, but I have a high set of expectations due to past experiences!

**Comment by lance** [comment]
@lkingland @jrangelramos @mgencur can this be closed now? We have e2e tests in place even if they are still a bit flakey.

**Comment by lkingland** [comment]
Yes, thanks!  E2E testing is now sufficient to close this, and is much less flaky now that 419 landed.

**Comment by jrangelramos** [comment]
Yes I aggree. It should be already closed .
