### ISSUE TITLE
`func create` should require "-l" flag; be strict about list of supported runtimes

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#553]
# Context
Many users did not expect `func create` to automatically create a Node HTTP project, the easiest way to resolve this is to simply require the -l flag when running `func create`

There may be a follow-on story to this one which asks the user if they want to save the language they specify as the default language, but that behavior is out of scope for this implementation. 

# Story 

**As Deandra the Developer**
**I want** func create to require me to specify a language
**So that** func does not assume I am a Node developer 
**And so that** I can see what languages func supports 

# Acceptance Criteria
- [ ] Reject `func create` without a the -l flag 
```
GIVEN I type out "func create someName" without an "-l" flag 
WHEN I hit enter 
THEN func returns an error which tells me I need to specify the -l flag
AND THEN func returns the list of currently supported runtimes
```

- [x] Reject non-supported runtimes
```
GIVEN I type "func create someName -l {someRuntime}"
AND {someRuntime} is not currently supported by func
WHEN I hit enter 
THEN func returns an error which tells me the runtime I specified is not currently supported
AND THEN func returns the list of currently supported runtimes
```

**Comment by lance** [comment]
AC #2 fixed in 
```
> ./func create -l asdf foo
Error: The language runtime 'asdf' is not recognized.
Available language runtimes are:
  go
  node
  nodejs
  python
  quarkus
  ruby
  rust
  springboot
  typescript
```

**Comment by lkingland** [comment]
I fundamentally have concerns about having required flags.  The other name for a flag is an "option".  They are definitionally optional.

The correct solution to this problem is to either 1) change this flag to an argument:  `func create node myFunction`, in which case the argument is required.  Or to 2) very visibly notify the user of the chosen default, and instruct them how to change this default in the future:
```
$ func create myFunc
You are creating a "node" Function.  To create a Function of a different Language Runtime, use the --language (-l) flag.  To change the global default language used when creating Functions and suppress this message, use:

   func config set language node --global

Created node Function in [path]
```

#1 is easier to implement.  #2 seems a bit friendlier (and is the direction `git` has gone).  I am in the process of implementing a global config system, at which time we can implement #2 (and is the reason I set myself as assigned to this issue).  I am open for suggestions!

**Comment by Shashankft9** [comment]
To me it seems like language runtime is something we shouldn't default to, because default in my head seems like a safe or most used option (which might be the option with http template) if I somehow forget to define, which in the case of language runtime is _none_, and if there still is a default, I'd suspect most of the times we are just making the user delete the directory once its created with a wrong runtime and run the command again with the desired runtime(which btw happened to me too when I started with func cli) - which I think could be improved upon if we just never create a directory if the language runtime is not provided. 

And if I look to kubectl cli, 
```
[root@k8s-master01 ~]# kubectl create deployment test
Error: required flag(s) "image" not set
```
Similar kind of behavior with the pack cli which asks me to provide either a builder or a builder when I try to build my code (note: its not a prompt, it just lets me know that I have to provide some value in the next run):
```
[root@k8s-master01 function-rust]# pack build docker.io/xyz/function-rust
Please select a default builder with:

        pack config default-builder <builder-image>
        ...
```
So I personally am not sure if we should do something different here - I can be very wrong on this but I think we should keep the ux similar to the likes of kubectl and such? As far as the definition of flag/option etc is considered, I couldn't find a proper set of definitions for their usage, what I found till now is more on the lines of _what the library or the particular software imposed_

On another note, I liked what @lkingland proposed in the PR here: https://github.com/knative-sandbox/kn-plugin-func/pull/647#pullrequestreview-803804535 (this involves making this flag required)
> simply remove the default from the flag. If in "confirm" mode they get a prompt, and if in non-confirm-mode they get an error stating language is required.

and then letting confirm mode be a setting (or even language runtime and maybe template?) that can be defaulted through `func config` 

PS: I am not really experienced with cli desicions like this, so please excuse if I said something silly :)

**Comment by lkingland** [comment]
In generaly I agree with you almost completely.  Your analysis and explanations are clear and understandable.  Thanks for taking the time to work this out.  We will be sure to arrive at a better solution for taking the effort.

A few points.  First, I would like to emulate the behavior of `git` above the behavior of `kubectl`.  This is (among other reasons) because our target audience is likely to have experience with `git`, and have it be their most-used command for day-to-day development.  Furthermore, our expected workflow will be very tightly tied to `git`, with the use of `kubectl` being almost never required.

Second, your second example of `pack` seems to agree completely with my second (and preferred!) suggestion of requesting that the user select a default to be used int he future.  So that seems good.

Finally, I also agree that the _only two truly required_ arguments for a new Function are 1) the language and 2) the name (let's ignore for the moment the need for a container registry, as that is intended to be removed as a requirement).  Here's a quick quick trip down memory lane: the initial POC I did (back when `func` was named `faas`) had the command `faas create <language> <name>`.  I still believe this to be the correct UX.

My suggestion is that we do what you say above:  we go ahead and implement our apparently agreed-upon path of: removing the default in the CLI, and either returning an error or prompting for input depending on if the user is in "confirm mode" (`--confirm`). 

I would love if we could revisit this issue with the whole team and propose that this flag be turned in to a required argument instead... but that shouldn't get in the way for now!

**Comment by zroubalik** [comment]
To add to the discussion on whether to print an error msg with list of runtimes vs promt with the runtime. 

As I mentioned https://github.com/knative-sandbox/kn-plugin-func/pull/647#discussion_r749391958, I prefer to display a prompt in this particular case. Because imho it is actually much faster and convenient to continue with the runtime selection in the prompt, instead of memorizing what is the correct runtime name (I know that this is a little bit made up argument, but for newcomers it might not be that straightforward), then rewriting the command, specifying the flag and typing the runtime and then confirming.

The `runtime` is actually a very important and fundamental piece in a function creation, it is not some random argument to specify some details, where users could introduce mistakes and typos (and where the validation and error printing makes sense).

But this is just my opinion and I might be obviously wrong :)

**Comment by lance** [comment]
Fixed in: https://github.com/knative-sandbox/kn-plugin-func/pull/647
