### ISSUE TITLE
Create should prompt for `cloudevents` when provided events, event, or ce as options for `cloudevents`

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#637]
```
GIVEN I have installed the func CLI
WHEN I  type `func create -l <lang> -t events` or similar
THEN I am presented with an error message asking if I meant "cloudevents"
```

**Comment by lance** [comment]
@omerbensaadon do you mean that the following commands should all result in the same thing - the creation of a function template for cloudevents? For example, all of the following commands should result in identical output - the creation of a Node.js project with a function signature accepting a CloudEvent?

* `func create -l node -t ce foo`
* `func create -l node -t event foo`
* `func create -l node -t events foo`

**Comment by zroubalik** [comment]
I inclined to support this. I have only one concern, wouldn't it make a problem or bring confusion to the external templates?

**Comment by lance** [comment]
> wouldn't it make a problem or bring confusion to the external templates?

I worry about that too. I'm entirely convinced that this aliasing is a good thing.

**Comment by dolfolife** [comment]
There are many ways a function can support events and CloudEvents is only one of them. Making the CLI use the implementation for cloudevents might create some confusion and it will make it harder to add other types of events. 

If our implementation for the function's experience is to align with Knative Eventing I am happy to add more words for the dictionary since Knative eventing docs say
```
Knative Eventing uses standard HTTP POST requests to send and receive events between event producers and sinks. 
These events conform to the CloudEvents specifications, which enables creating, parsing, sending, and receiving events in any programming language.
```

No matter the way we want to specify what `events` are,  I can see the usage of `ce` as short of cloudevents.

> wouldn't it make a problem or bring confusion to the external templates?
Is there a way to make the code of `understanding the request` from the CLI perspective more flexible while making strict implementation for types of function inputs? external and all templates only need to build the type of function's input we support (generic and CE) and how the user asks for them can be abstracted from the template guide/spec.

**Comment by lance** [comment]
The requested behavior to ask, "did you mean 'cloudevents'" is very specifically geared towards an error message in the case of cloudevent templates. The current behavior, which was implemented after this issue was created, fixes this in a more generic but still acceptable way, in my opinion. I think this issue should be closed. /cc @nainaz @lkingland @zroubalik @matejvasek @salaboy 

```
❯ func create -l node -t events
Error: The template 'events' was not found for language runtime 'node'.
Available templates for this language runtime are:
  cloudevents
  http
  tmpls/hello-world

```

**Comment by nainaz** [comment]
I agree with error message and suggestions for the options. 
Aliasing would open a whole new set of possibilities and complications. 
Agree that we can close the issue.
