### ISSUE TITLE
Verbose flag for repository list command doesn't work

### ISSUE THREAD

**Issue by lstocchi** [knative-sandbox/kn-plugin-func#891]
By reading https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/commands.md#list-1 the flag `-v` or `--verbose` should also list the URLs of each repo but it only shows the names as if the flag it is not used

```
$ func repository list
default
myrepo
$ func repository list -v
default
myrepo
```

**Comment by matejvasek** [comment]
Looks like there are two issue:
* URI is not printed for local FS repositories (the one starting with `file://`)
* For git repositories the URI should be printed but for some reason they are not printed at all.

**Comment by matejvasek** [comment]
Hm for HTTP git repo the derived URI is `file:///home/mvasek/.config/func/repositories/https:` which is totally wrong.

**Comment by matejvasek** [comment]
The `repository` sub-command takes flags `repositories` whereas for the `create` sub command it's singular flag `repository`. Why? Also why the `function.Repositories` struct has both `path` and `remote`? Wouldn't be URI enough?

cc @lance @lkingland

**Comment by lkingland** [comment]
Create actually takes both but the plural is not documented to avoid confusion. "Repositories" means "use the installed repositories which are located on disk at this location" (default ~/.config/func/repositores) whereas the singular flat "repository" means "ignore repositories on/disk and use exactly this repository". For example at a remote URL.

**Comment by matejvasek** [comment]
@lkingland  @lance  Could we merge these (non)plural flags to just one flag? I find it really confusing.

**Comment by zroubalik** [comment]
> @lkingland @lance Could we merge these (non)plural flags to just one flag? I find it really confusing.

+100

**Comment by lkingland** [comment]
> we merge these (non)plural flags to just one flag?

I'm sorry but these two settings have very clearly different purposes and can not be merged.  I do have a suggestion, however.  Since the path to repositories on disk is very unlikely to be used in most situations (perhaps for running in an automated environment, or in a headless, airgapped scenario), we can remove this as a flag, leaving it only as a configuration setting.  This will mean the only flag readily displayed to users is `--repository`.  We can also rename the other setting to `FUNC_REPOSITORIES_PATH` to differentiate it further from the "use this repository instead of installed repos" `--repository` setting.

If that, along with further clarification in help text, is not sufficiently clarifying, we can perhaps discuss removing the `FUNC_REPOSITORIES_PATH` setting entirely, leaving it hard-coded to be `XDG_CONFIG_HOME/func/repositories`; but I think this is a bit too far, and instead deemphasizing the setting, and moving it to a Config-only setting (not a flag) should take care of the confusion!

**Comment by lkingland** [comment]
> Also why the `function.Repositories` struct has both `path` and `remote`? Wouldn't be URI enough?

Here
```go
type Repositories struct {
  // Optional path to extensible repositories on disk.  Blank indicates not
  // to use extensible
  path string

  // Optional uri of a single repo to use in leau of embedded and extensible.
  // Enables single-repository mode.  This replaces the default embedded repo
  // and extended repositories.  This is an important mode for both diskless
  // (config-less) operation, such as security-restrited environments, and for
  // running as a library in which case environmental settings should be
  // ignored in favor of a more functional approach in which only inputs affect
  // outputs.
  remote string
```

Unfortunately no it would not be sufficient to use just a UR, since one is a 1:1 relationship, the other is a 1:many.  It perhaps might help to reiterate that the original requirements for the Extensible Templates Repositories system was to have it function in two modes:  using locally installed template repositories, or alternately to ignore installed repositories and use a single, remote git repository directly.  Modes in an app always cause irreduceable conplexity.  Some have gone so far as to claim all modes should be eradicated from software entirely.  I am inclined to agree, but as a `vi` user, I do not hold that position too strongly.  sometimes modes help.  And I want to be able to say both:

`func create -l go -t boson/quickstart-example1`
OR
`func create -l go -t http --repository git@github.com:....`

I do think both are useful, in their own way, despite the need for modes.

**Comment by lkingland** [comment]
I have created an issue to track differentiating these two settings that I hope captures the core of the situation:

https://github.com/knative-sandbox/kn-plugin-func/issues/896

**Comment by sudhirverma** [comment]
it would be good to have a list command in structured output (JSON or YAML) format.

**Comment by lance** [comment]
@sudhirverma take a look at the `--output` flag.

**Comment by matejvasek** [comment]
I think that for the `repo` sub-command the output is fixed, there is no `--output` flags,
some other command support it however.

**Comment by lance** [comment]
> I think that for the `repo` sub-command the output is fixed, there is no `--output` flags, some other command support it however.

Ahh right, I see. I was just considering `func list` not `func repo list`.
