### ISSUE TITLE
Add support for s2i builds

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#908]
The CLI is structured such that the builder is an interface. Currently there is a buildpack implementation, and a mock implementation for testing. We should additionally support s2i as a build strategy.

https://github.com/knative-sandbox/kn-plugin-func/blob/cad0a04276cbd0fe15a83afb68dc5fd680f47d48/client.go#L66-L70

**Comment by lance** [comment]
@lkingland in https://github.com/knative-sandbox/kn-plugin-func/pull/923 you mentioned that it was the first step. Could you add some tasks here identifying the additional steps required to complete the feature?

**Comment by lkingland** [comment]
In order to fully support S2I builds, I would presume we want to support them for all our "core" language runtimes, and for both docker and podman.    #923 proves the concept via the Node.js S2I builder, so unless I am misguided, the full list would be:

- [X] Node S2I Builder (#923)
- [ ] Typescript S2I Builder
- [ ] Python S3I Builder
- [ ] Go S2I Builder
- [ ] Quarkus S2I Builder
- [ ] Rust S2I Builder
- [ ] Podman Support Validation

**Comment by lance** [comment]
@lkingland I believe the immediate goal is to have Quarkus and Node.js/TypeScript as S2I builders. So that's a success - yay! 🎊 

As for the remainder.

- Python: https://catalog.redhat.com/software/containers/ubi8/python-39/6065b24eb92fbda3a4c65d8f - I hacked around on this and got it to work without too much trouble by adding an `app.sh` file with the contents `python -m parliament .` to a Python function project and setting the builder in my func.yaml. I don't love having to add another file to the template tree though. Especially if it's not used by default. We could set environment variables, but I think the only one that makes sense given how the Parliament module works is `APP_MODULE`, but I've never used gunicorn or whatever. (I'm not a Python dev!) 🤣 

- Go: https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1 - this one is trickier as you know, since we need that wrapper code. I do not think this is a priority for Red Hat or the upstream, however. The buildpacks from Paketo are a much better path forward, in my opinion.

- Rust: I don't think Red Hat produces a Rust language S2I builder image - we can probably set that aside for the time being. We don't want to be in the business of producing a Rust S2I builder image ourselves. As it went with boson buildpacks, I don't see that as being fruitful in the long term.

**Comment by lkingland** [comment]
Thanks for figuring out the Python magic knock sequence.  I tried adding the `app.sh` but was missing the explicit call to parliament.

It's nice to know we can move forward with what we have now, because we have support for our immediate goals.

I'd like to try perhaps using a thin container layer which adds S2I-specific requirements such that we can support Python and Go, without needing to add those extra (seemingly superfluous to the Function developer) to the templates themselves.  Perhaps Rust being a future enhancement.

**Comment by lance** [comment]
Will open issues for Python, Go, Rust and Podman validation.
