### ISSUE TITLE
Improve Builder Flag Names

### ISSUE THREAD

**Issue by lkingland** [knative-sandbox/kn-plugin-func#942]
The `--builder-image` flag introduced in #923 presents possible confusion with `--builder`.

```go
cmd.Flags().StringP("builder", "b", "pack", "builder to use when creating the underlying image. Currently supported builders are 'pack' and 's2i'.")
cmd.Flags().StringP("builder-image", "", "", "builder image, either an image name or a mapping name.\nSpecified value is stored in func.yaml for subsequent builds. ($FUNC_BUILDER_IMAGE)")
```
As is mentioned during code review, we should take the time to consider possible alternative names or a wholesale refactor of this feature.

**Comment by lance** [comment]
I suggest using `--strategy` and `-s` for the builder type, e.g. `buildpack` or `s2i`. I can even see a `docker` strategy being reasonable at some point in the future, to allow developers to really customize the resulting image. And use `builder` or `builder-image` for the image name. I think `builder` might be better because it doesn't tie us down to an image as the only reasonable type of value.

**Comment by zroubalik** [comment]
I like the proposal by @lance

**Comment by lkingland** [comment]
> I think `builder` might be better

Agreed.  If we use `--strategy`, there is no longer a name collision on `--bulder` and we can move `--builder-image` back to just
 `--builder`.

**Comment by lkingland** [comment]
I think the initial confusion was caused more by a mismatch between the flag names and the structure fields, and now that we have refactored a bit, they are in sync.   Since the code is now aligned with these flag names `builder` and `builder-image`,  I would strongly suggest that we stick with _these_ names, since I believe the underlying reason for the confusion has been resolved.
