### ISSUE TITLE
broken in link in nodejs template

### ISSUE THREAD

**Issue by csantanapr** [knative-sandbox/kn-plugin-func#998]
creating a http or cloudevent function with `func create` and using node, the index.js has a link to the docs about `context` and is broken
```
 * See: https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/nodejs.md#the-context-object
 */
```

**Comment by csantanapr** [comment]
It should be https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/function-developers/nodejs.md#the-context-object

I was trying to figure out why the `context.log.info` lines was not printing

**Comment by lance** [comment]
/kind bug
/kind documentation
The `context.log.info` uses the `FUNC_LOG_LEVEL` environment variable to determine when to log things. I believe the default is set to `warn` not `info`. But this should at least be documented in the template.

**Comment by lance** [comment]
@csantanapr that turns out to be a bug. A fix for it landed here https://github.com/boson-project/faas-js-runtime/pull/110 but the release of faas-js-runtime with that fix is not included in the current templates for `func`. You can change that by modifying the dependency version for faas-js-runtime in your package.json file to `0.9.0`.

**Comment by lance** [comment]
Closing. Fixed in https://github.com/knative-sandbox/kn-plugin-func/pull/1000
